#!/usr/bin/env python3
"""
Dump all prologue packets generated by the script_generator for SPMV.
"""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from pymtl3 import *
from pymtl3.passes.sim.PrepareSimPass import b1

from lib.messages import *
from lib.opt_type import *
from lib.util.common import *

# Same parameters as CgraRTL_spmv_test_from_yaml.py
x_tiles = 4
y_tiles = 4
data_bitwidth = 32
tile_ports = 4
num_tile_inports = tile_ports
num_tile_outports = tile_ports
num_fu_inports = 4
num_fu_outports = 2
num_routing_outports = num_tile_outports + num_fu_inports
ctrl_mem_size = 16
data_mem_size_global = 128
data_mem_size_per_bank = 16
num_banks_per_cgra = 2
num_cgra_columns = 4
num_cgra_rows = 1
num_cgras = num_cgra_columns * num_cgra_rows
num_registers_per_reg_bank = 8
per_cgra_data_size = int(data_mem_size_global / num_cgras)

TileInType = mk_bits(clog2(num_tile_inports + num_fu_inports + 1))
FuInType = mk_bits(clog2(num_fu_inports + 1))
FuOutType = mk_bits(clog2(num_fu_outports + 1))
addr_nbits = clog2(data_mem_size_global)
num_tiles = x_tiles * y_tiles
num_rd_tiles = x_tiles + y_tiles - 1

DataAddrType = mk_bits(addr_nbits)
RegIdxType = mk_bits(clog2(num_registers_per_reg_bank))
DataType = mk_data(data_bitwidth, 1)
b2 = mk_bits(2)

CtrlType = mk_ctrl(num_fu_inports, num_fu_outports,
                    num_tile_inports, num_tile_outports,
                    num_registers_per_reg_bank)
CtrlAddrType = mk_bits(clog2(ctrl_mem_size))
CgraPayloadType = mk_cgra_payload(DataType, DataAddrType, CtrlType, CtrlAddrType)
IntraCgraPktType = mk_intra_cgra_pkt(num_cgra_columns, num_cgra_rows,
                                      num_tiles, CgraPayloadType)

kCtrlCountPerIter = 15
kTotalCtrlSteps = kCtrlCountPerIter * 4 + 10

from validation.script_generator import ScriptFactory
script_factory = ScriptFactory(
    path="validation/test/spmv.yaml",
    CtrlType=CtrlType,
    IntraCgraPktType=IntraCgraPktType,
    CgraPayloadType=CgraPayloadType,
    TileInType=TileInType,
    FuOutType=FuOutType,
    CMD_CONFIG_input=CMD_CONFIG,
    FuInType=FuInType,
    ii=kCtrlCountPerIter,
    loop_times=kTotalCtrlSteps,
    CMD_CONST_input=CMD_CONST,
    CMD_CONFIG_COUNT_PER_ITER_input=CMD_CONFIG_COUNT_PER_ITER,
    CMD_CONFIG_TOTAL_CTRL_COUNT_input=CMD_CONFIG_TOTAL_CTRL_COUNT,
    CMD_CONFIG_PROLOGUE_FU_input=CMD_CONFIG_PROLOGUE_FU,
    CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input=CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR,
    CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input=CMD_CONFIG_PROLOGUE_FU_CROSSBAR,
    CMD_LAUNCH_input=CMD_LAUNCH,
    DataType=DataType,
    B1Type=b1,
    B2Type=b2,
    RegIdxType=RegIdxType,
    CtrlAddrType=CtrlAddrType,
    DataAddrType=DataAddrType,
    num_registers_per_reg_bank=num_registers_per_reg_bank,
)

pkts_dict = script_factory.makeVectorCGRAPkts()

# Print prologue packets for each tile
for (x, y), pkts in sorted(pkts_dict.items()):
    tid = x + y * 4
    print(f"\n=== Tile {tid} (col={x}, row={y}) ===")
    for pkt in pkts:
        cmd = int(pkt.payload.cmd)
        if cmd == CMD_CONFIG_PROLOGUE_FU:
            addr = int(pkt.payload.ctrl_addr)
            count = int(pkt.payload.data.payload)
            print(f"  PROLOGUE_FU: step={addr}, count={count}")
        elif cmd == CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR:
            addr = int(pkt.payload.ctrl_addr)
            count = int(pkt.payload.data.payload)
            # Extract which inport is being prologued
            rxo = pkt.payload.ctrl.routing_xbar_outport
            inport_idx = int(rxo[0])
            dir_names = {1: 'NORTH', 2: 'SOUTH', 3: 'WEST', 4: 'EAST'}
            dir_name = dir_names.get(inport_idx, f'idx{inport_idx}')
            print(f"  PROLOGUE_ROUTING_XBAR: step={addr}, inport={dir_name}(sel={inport_idx}), count={count}")
        elif cmd == CMD_CONFIG_PROLOGUE_FU_CROSSBAR:
            addr = int(pkt.payload.ctrl_addr)
            count = int(pkt.payload.data.payload)
            print(f"  PROLOGUE_FU_XBAR: step={addr}, count={count}")
