// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vcgra_test.h for the primary calling header

#ifndef VERILATED_VCGRA_TEST_CGRARTL___05F302B5D787F9CA139_H_
#define VERILATED_VCGRA_TEST_CGRARTL___05F302B5D787F9CA139_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vcgra_test_ChannelRTL___05Ff70d05b62b8bbe7b;
class Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5;
class Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c;
class Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f;
class Vcgra_test_SwitchUnitRTL___05Feabc1ec732b8a20f;
class Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194;
class Vcgra_test_XbarBypassQueueRTL___05F1d3f6e8e4814a1bb;


class Vcgra_test__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vcgra_test_CgraRTL___05F302b5d787f9ca139 final : public VerilatedModule {
  public:
    // CELLS
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F0;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F1;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F2;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F3;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F4;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F5;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F6;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F7;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F8;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F9;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F10;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F11;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F12;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F13;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F14;
    Vcgra_test_TileRTL___05Fa6dbbcbe0fd05194* __PVT__tile___05F15;
    Vcgra_test_ChannelRTL___05Ff70d05b62b8bbe7b* __PVT__controller__DOT__recv_from_tile_load_request_pkt_queue;
    Vcgra_test_ChannelRTL___05Ff70d05b62b8bbe7b* __PVT__controller__DOT__recv_from_tile_load_response_pkt_queue;
    Vcgra_test_ChannelRTL___05Ff70d05b62b8bbe7b* __PVT__controller__DOT__recv_from_tile_store_request_pkt_queue;
    Vcgra_test_ChannelRTL___05Ff70d05b62b8bbe7b* __PVT__controller__DOT__send_to_mem_load_request_queue;
    Vcgra_test_ChannelRTL___05Ff70d05b62b8bbe7b* __PVT__controller__DOT__send_to_mem_store_request_queue;
    Vcgra_test_ChannelRTL___05Ff70d05b62b8bbe7b* __PVT__controller__DOT__send_to_tile_load_response_queue;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F0;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F1;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F2;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F3;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F4;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F5;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F6;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F7;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F8;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F9;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F10;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F11;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F12;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F13;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F14;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F15;
    Vcgra_test_RecvRTL2CreditSendRTL___05F78338e65a32ae52c* __PVT__ctrl_ring__DOT__recv_adp___05F16;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F0;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F1;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F2;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F3;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F4;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F5;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F6;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F7;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F8;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F9;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F10;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F11;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F12;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F13;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F14;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F15;
    Vcgra_test_RingRouterRTL___05Ffdc7e4156c73012f* __PVT__ctrl_ring__DOT__routers___05F16;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F0;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F1;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F2;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F3;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F4;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F5;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F6;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F7;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F8;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F9;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F10;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F11;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F12;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F13;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F14;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F15;
    Vcgra_test_CreditRecvRTL2SendRTL___05Fc5b3263f77da2ee5* __PVT__ctrl_ring__DOT__send_adp___05F16;
    Vcgra_test_XbarBypassQueueRTL___05F1d3f6e8e4814a1bb* __PVT__data_mem__DOT__read_crossbar;
    Vcgra_test_XbarBypassQueueRTL___05F1d3f6e8e4814a1bb* __PVT__data_mem__DOT__write_crossbar;
    Vcgra_test_SwitchUnitRTL___05Feabc1ec732b8a20f* __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05F0;
    Vcgra_test_SwitchUnitRTL___05Feabc1ec732b8a20f* __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05F1;
    Vcgra_test_SwitchUnitRTL___05Feabc1ec732b8a20f* __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05F2;
    Vcgra_test_SwitchUnitRTL___05Feabc1ec732b8a20f* __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05F3;
    Vcgra_test_SwitchUnitRTL___05Feabc1ec732b8a20f* __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05F4;
    Vcgra_test_SwitchUnitRTL___05Feabc1ec732b8a20f* __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05F5;
    Vcgra_test_SwitchUnitRTL___05Feabc1ec732b8a20f* __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05F6;
    Vcgra_test_SwitchUnitRTL___05Feabc1ec732b8a20f* __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05F7;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(address_lower,6,0);
        VL_IN8(address_upper,6,0);
        VL_IN8(cgra_id,1,0);
        VL_IN8(reset,0,0);
        VL_OUT8(recv_from_cpu_pkt___05Frdy,0,0);
        VL_IN8(recv_from_cpu_pkt___05Fval,0,0);
        VL_OUT8(recv_from_inter_cgra_noc___05Frdy,0,0);
        VL_IN8(recv_from_inter_cgra_noc___05Fval,0,0);
        VL_IN8(send_to_cpu_pkt___05Frdy,0,0);
        VL_OUT8(send_to_cpu_pkt___05Fval,0,0);
        VL_IN8(send_to_inter_cgra_noc___05Frdy,0,0);
        VL_OUT8(send_to_inter_cgra_noc___05Fval,0,0);
        CData/*0:0*/ __PVT__controller___05Frecv_from_ctrl_ring_pkt___05Frdy;
        CData/*0:0*/ __PVT__controller___05Frecv_from_inter_cgra_noc___05Frdy;
        CData/*0:0*/ __PVT__controller___05Fsend_to_ctrl_ring_pkt___05Fval;
        CData/*0:0*/ __PVT__controller__DOT__global_reduce_unit___05Frecv_count___05Fval;
        CData/*0:0*/ __PVT__controller__DOT__global_reduce_unit___05Frecv_data___05Frdy;
        CData/*0:0*/ __PVT__controller__DOT__global_reduce_unit___05Frecv_data___05Fval;
        CData/*0:0*/ __PVT__controller__DOT__global_reduce_unit___05Fsend___05Frdy;
        CData/*0:0*/ __PVT__controller__DOT__global_reduce_unit___05Fsend___05Fval;
        CData/*0:0*/ __PVT__controller__DOT__send_to_mem_load_request_queue___05Frecv___05Fval;
        CData/*0:0*/ __PVT__controller__DOT__send_to_mem_store_request_queue___05Frecv___05Fval;
        CData/*0:0*/ __PVT__controller__DOT__send_to_tile_load_response_queue___05Frecv___05Fval;
        CData/*1:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl__DOT__send_xfer;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl__DOT__send_xfer;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl__DOT__send_xfer;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__ctrl__DOT__send_xfer;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__ctrl__DOT__send_xfer;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__ctrl__DOT__send_xfer;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__route_units___05F0__DOT__out_dir;
        CData/*0:0*/ controller__DOT__crossbar__DOT__route_units___05F0__DOT____Vlvbound_h73cc810d__0;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__route_units___05F1__DOT__out_dir;
        CData/*0:0*/ controller__DOT__crossbar__DOT__route_units___05F1__DOT____Vlvbound_h73cc810d__0;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__route_units___05F2__DOT__out_dir;
        CData/*0:0*/ controller__DOT__crossbar__DOT__route_units___05F2__DOT____Vlvbound_h73cc810d__0;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__route_units___05F3__DOT__out_dir;
        CData/*0:0*/ controller__DOT__crossbar__DOT__route_units___05F3__DOT____Vlvbound_h73cc810d__0;
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__route_units___05F4__DOT__out_dir;
        CData/*0:0*/ controller__DOT__crossbar__DOT__route_units___05F4__DOT____Vlvbound_h73cc810d__0;
    };
    struct {
        CData/*0:0*/ __PVT__controller__DOT__crossbar__DOT__route_units___05F5__DOT__out_dir;
        CData/*0:0*/ controller__DOT__crossbar__DOT__route_units___05F5__DOT____Vlvbound_h73cc810d__0;
        CData/*5:0*/ __PVT__controller__DOT__crossbar__DOT__switch_units___05F0__DOT__arbiter___05Fgrants;
        CData/*2:0*/ __PVT__controller__DOT__crossbar__DOT__switch_units___05F0__DOT__encoder___05Fout;
        CData/*5:0*/ __PVT__controller__DOT__crossbar__DOT__switch_units___05F0__DOT__arbiter__DOT__priority_reg___05Fout;
        CData/*0:0*/ controller__DOT__crossbar__DOT__switch_units___05F0__DOT__arbiter__DOT____Vlvbound_hd2f3a35b__0;
        CData/*0:0*/ controller__DOT__crossbar__DOT__switch_units___05F0__DOT__arbiter__DOT____Vlvbound_hd2f3a35b__1;
        CData/*0:0*/ controller__DOT__crossbar__DOT__switch_units___05F0__DOT__arbiter__DOT____Vlvbound_hb2227637__0;
        CData/*0:0*/ controller__DOT__crossbar__DOT__switch_units___05F0__DOT__arbiter__DOT____Vlvbound_hb2227637__1;
        CData/*4:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__ctrl___05Fwen;
        CData/*3:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__ctrl__DOT__send_xfer;
        CData/*3:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__ctrl__DOT__send_xfer;
        CData/*0:0*/ __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__ctrl__DOT__send_xfer;
        CData/*0:0*/ __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl___05Fsend_val;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl___05Fsend_val;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*1:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl___05Fcount;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl___05Fsend_val;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl___05Fwen;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl__DOT__head;
        CData/*0:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__ctrl__DOT__tail;
        CData/*2:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__route_units___05F0__DOT__out_dir;
        CData/*2:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__route_units___05F1__DOT__out_dir;
        CData/*2:0*/ __PVT__data_mem__DOT__response_crossbar__DOT__route_units___05F2__DOT__out_dir;
        SData/*11:0*/ __PVT__controller__DOT__crossbar__DOT__switch_units___05F0__DOT__arbiter__DOT__grants_int;
        SData/*12:0*/ __PVT__controller__DOT__crossbar__DOT__switch_units___05F0__DOT__arbiter__DOT__kills;
        VL_INW(recv_from_cpu_pkt___05Fmsg,228,0,8);
        VL_INW(recv_from_inter_cgra_noc___05Fmsg,232,0,8);
        VL_OUTW(send_to_cpu_pkt___05Fmsg,228,0,8);
        VL_OUTW(send_to_inter_cgra_noc___05Fmsg,232,0,8);
        VlWide<8>/*228:0*/ __PVT__controller___05Fsend_to_ctrl_ring_pkt___05Fmsg;
        VlWide<8>/*232:0*/ __PVT__controller___05Fsend_to_inter_cgra_noc___05Fmsg;
        VlWide<8>/*232:0*/ __PVT__data_mem___05Fsend_to_noc_load_request_pkt___05Fmsg;
        VlWide<8>/*232:0*/ __PVT__data_mem___05Fsend_to_noc_load_response_pkt___05Fmsg;
        VlWide<8>/*232:0*/ __PVT__data_mem___05Fsend_to_noc_store_pkt___05Fmsg;
        VlWide<8>/*232:0*/ __PVT__controller__DOT__global_reduce_unit___05Frecv_count___05Fmsg;
        VlWide<8>/*232:0*/ __PVT__controller__DOT__global_reduce_unit___05Frecv_data___05Fmsg;
        VlWide<8>/*233:0*/ __PVT__controller__DOT__global_reduce_unit___05Fsend___05Fmsg;
        VlWide<8>/*232:0*/ __PVT__controller__DOT__send_to_mem_load_request_queue___05Frecv___05Fmsg;
        VlWide<8>/*232:0*/ __PVT__controller__DOT__send_to_mem_store_request_queue___05Frecv___05Fmsg;
        VlWide<8>/*232:0*/ __PVT__controller__DOT__send_to_tile_load_response_queue___05Frecv___05Fmsg;
        VlWide<3>/*66:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__receiving_count;
        VlWide<3>/*66:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__reduce_add_value;
        VlWide<3>/*66:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__reduce_mul_value;
        VlWide<3>/*66:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__sending_count;
        VlWide<3>/*66:0*/ __PVT__controller__DOT__global_reduce_unit__DOT__target_count;
    };
    struct {
        VL_INW(recv_data_on_boundary_east___05Fmsg[4],66,0,3);
        VL_OUT8(recv_data_on_boundary_east___05Frdy[4],0,0);
        VL_IN8(recv_data_on_boundary_east___05Fval[4],0,0);
        VL_INW(recv_data_on_boundary_north___05Fmsg[4],66,0,3);
        VL_OUT8(recv_data_on_boundary_north___05Frdy[4],0,0);
        VL_IN8(recv_data_on_boundary_north___05Fval[4],0,0);
        VL_INW(recv_data_on_boundary_south___05Fmsg[4],66,0,3);
        VL_OUT8(recv_data_on_boundary_south___05Frdy[4],0,0);
        VL_IN8(recv_data_on_boundary_south___05Fval[4],0,0);
        VL_INW(recv_data_on_boundary_west___05Fmsg[4],66,0,3);
        VL_OUT8(recv_data_on_boundary_west___05Frdy[4],0,0);
        VL_IN8(recv_data_on_boundary_west___05Fval[4],0,0);
        VL_OUTW(send_data_on_boundary_east___05Fmsg[4],66,0,3);
        VL_IN8(send_data_on_boundary_east___05Frdy[4],0,0);
        VL_OUT8(send_data_on_boundary_east___05Fval[4],0,0);
        VL_OUTW(send_data_on_boundary_north___05Fmsg[4],66,0,3);
        VL_IN8(send_data_on_boundary_north___05Frdy[4],0,0);
        VL_OUT8(send_data_on_boundary_north___05Fval[4],0,0);
        VL_OUTW(send_data_on_boundary_south___05Fmsg[4],66,0,3);
        VL_IN8(send_data_on_boundary_south___05Frdy[4],0,0);
        VL_OUT8(send_data_on_boundary_south___05Fval[4],0,0);
        VL_OUTW(send_data_on_boundary_west___05Fmsg[4],66,0,3);
        VL_IN8(send_data_on_boundary_west___05Frdy[4],0,0);
        VL_OUT8(send_data_on_boundary_west___05Fval[4],0,0);
        VlUnpacked<CData/*6:0*/, 7> __PVT__data_mem___05Frecv_raddr___05Fmsg;
        VlUnpacked<CData/*0:0*/, 7> __PVT__data_mem___05Frecv_raddr___05Frdy;
        VlUnpacked<CData/*0:0*/, 7> __PVT__data_mem___05Frecv_raddr___05Fval;
        VlUnpacked<CData/*6:0*/, 7> __PVT__data_mem___05Frecv_waddr___05Fmsg;
        VlUnpacked<CData/*0:0*/, 7> __PVT__data_mem___05Frecv_waddr___05Frdy;
        VlUnpacked<CData/*0:0*/, 7> __PVT__data_mem___05Frecv_waddr___05Fval;
        VlUnpacked<VlWide<3>/*66:0*/, 7> __PVT__data_mem___05Frecv_wdata___05Fmsg;
        VlUnpacked<CData/*0:0*/, 7> __PVT__data_mem___05Frecv_wdata___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 7> __PVT__data_mem___05Fsend_rdata___05Fmsg;
        VlUnpacked<CData/*0:0*/, 7> __PVT__data_mem___05Fsend_rdata___05Frdy;
        VlUnpacked<CData/*0:0*/, 7> __PVT__data_mem___05Fsend_rdata___05Fval;
        VlUnpacked<VlUnpacked<VlWide<3>/*66:0*/, 4>, 16> __PVT__tile___05Frecv_data___05Fmsg;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 4>, 16> __PVT__tile___05Frecv_data___05Frdy;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 4>, 16> __PVT__tile___05Frecv_data___05Fval;
        VlUnpacked<VlUnpacked<VlWide<3>/*66:0*/, 4>, 16> __PVT__tile___05Fsend_data___05Fmsg;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 4>, 16> __PVT__tile___05Fsend_data___05Frdy;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 4>, 16> __PVT__tile___05Fsend_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F0__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F0__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F0__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F0__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F0__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F0__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F1__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F1__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F1__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F1__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F1__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F1__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F2__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F2__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F2__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F2__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F2__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F2__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F3__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F3__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F3__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F3__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F3__recv_data___05Frdy;
    };
    struct {
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F3__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F4__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F4__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F4__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F4__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F4__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F4__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F5__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F5__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F5__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F5__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F5__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F5__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F6__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F6__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F6__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F6__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F6__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F6__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F7__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F7__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F7__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F7__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F7__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F7__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F8__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F8__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F8__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F8__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F8__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F8__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F9__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F9__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F9__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F9__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F9__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F9__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F10__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F10__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F10__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F10__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F10__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F10__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F11__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F11__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F11__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F11__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F11__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F11__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F12__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F12__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F12__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F12__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F12__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F12__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F13__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F13__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F13__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F13__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F13__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F13__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F14__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F14__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F14__send_data___05Fmsg;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F14__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F14__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F14__recv_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F15__send_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F15__send_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellout__tile___05F15__send_data___05Fmsg;
        VlUnpacked<CData/*0:0*/, 4> __Vcellinp__tile___05F15__recv_data___05Fval;
        VlUnpacked<CData/*0:0*/, 4> __Vcellout__tile___05F15__recv_data___05Frdy;
        VlUnpacked<VlWide<3>/*66:0*/, 4> __Vcellinp__tile___05F15__recv_data___05Fmsg;
        VlUnpacked<CData/*1:0*/, 4> __PVT__controller__DOT__addr2controller_lut;
        VlUnpacked<CData/*0:0*/, 4> __PVT__controller__DOT__idTo2d_x_lut;
        VlUnpacked<CData/*0:0*/, 4> __PVT__controller__DOT__idTo2d_y_lut;
        VlUnpacked<VlWide<8>/*233:0*/, 6> __PVT__controller__DOT__crossbar___05Frecv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 6> __PVT__controller__DOT__crossbar___05Frecv___05Frdy;
        VlUnpacked<CData/*0:0*/, 6> __PVT__controller__DOT__crossbar___05Frecv___05Fval;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar___05Fsend___05Fmsg;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar___05Fsend___05Frdy;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar___05Fsend___05Fval;
        VlUnpacked<VlUnpacked<VlWide<8>/*233:0*/, 1>, 6> __PVT__controller__DOT__crossbar__DOT__route_units___05Fsend___05Fmsg;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 1>, 6> __PVT__controller__DOT__crossbar__DOT__route_units___05Fsend___05Frdy;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 1>, 6> __PVT__controller__DOT__crossbar__DOT__route_units___05Fsend___05Fval;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F0__send___05Fval;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellinp__route_units___05F0__send___05Frdy;
        VlUnpacked<VlWide<8>/*233:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F0__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F1__send___05Fval;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellinp__route_units___05F1__send___05Frdy;
        VlUnpacked<VlWide<8>/*233:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F1__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F2__send___05Fval;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellinp__route_units___05F2__send___05Frdy;
        VlUnpacked<VlWide<8>/*233:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F2__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F3__send___05Fval;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellinp__route_units___05F3__send___05Frdy;
        VlUnpacked<VlWide<8>/*233:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F3__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F4__send___05Fval;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellinp__route_units___05F4__send___05Frdy;
        VlUnpacked<VlWide<8>/*233:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F4__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F5__send___05Fval;
        VlUnpacked<CData/*0:0*/, 1> controller__DOT__crossbar__DOT____Vcellinp__route_units___05F5__send___05Frdy;
        VlUnpacked<VlWide<8>/*233:0*/, 1> controller__DOT__crossbar__DOT____Vcellout__route_units___05F5__send___05Fmsg;
        VlUnpacked<VlUnpacked<VlWide<8>/*233:0*/, 6>, 1> __PVT__controller__DOT__crossbar__DOT__switch_units___05Frecv___05Fmsg;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 6>, 1> __PVT__controller__DOT__crossbar__DOT__switch_units___05Frecv___05Frdy;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 6>, 1> __PVT__controller__DOT__crossbar__DOT__switch_units___05Frecv___05Fval;
        VlUnpacked<CData/*0:0*/, 6> controller__DOT__crossbar__DOT____Vcellinp__switch_units___05F0__recv___05Fval;
        VlUnpacked<CData/*0:0*/, 6> controller__DOT__crossbar__DOT____Vcellout__switch_units___05F0__recv___05Frdy;
        VlUnpacked<VlWide<8>/*233:0*/, 6> controller__DOT__crossbar__DOT____Vcellinp__switch_units___05F0__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<8>/*233:0*/, 2> __PVT__controller__DOT__crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<8>/*233:0*/, 2> __PVT__controller__DOT__crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<8>/*233:0*/, 2> __PVT__controller__DOT__crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
    };
    struct {
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<8>/*233:0*/, 2> __PVT__controller__DOT__crossbar__DOT__input_units___05F3__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<8>/*233:0*/, 2> __PVT__controller__DOT__crossbar__DOT__input_units___05F4__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<8>/*233:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<8>/*233:0*/, 2> __PVT__controller__DOT__crossbar__DOT__input_units___05F5__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<VlWide<8>/*233:0*/, 6> __PVT__controller__DOT__crossbar__DOT__switch_units___05F0__DOT__mux___05Fin_;
        VlUnpacked<CData/*3:0*/, 1> __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<8>/*232:0*/, 1> __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*3:0*/, 1> __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<8>/*232:0*/, 1> __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<8>/*232:0*/, 16> __PVT__controller__DOT__global_reduce_unit__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<8>/*228:0*/, 1> __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<8>/*228:0*/, 1> __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<8>/*228:0*/, 2> __PVT__controller__DOT__recv_from_cpu_pkt_queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<8>/*228:0*/, 1> __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<8>/*228:0*/, 1> __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<8>/*228:0*/, 2> __PVT__controller__DOT__send_to_cpu_pkt_queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<CData/*0:0*/, 17> __PVT__ctrl_ring__DOT__recv_adp___05Fsend___05Fen;
        VlUnpacked<VlWide<8>/*228:0*/, 17> __PVT__ctrl_ring__DOT__recv_adp___05Fsend___05Fmsg;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 17> __PVT__ctrl_ring__DOT__recv_adp___05Fsend___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F0__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F1__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F2__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F3__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F4__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F5__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F6__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F7__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F8__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F9__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F10__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F11__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F12__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F13__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F14__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F15__send___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellinp__recv_adp___05F16__send___05Fyum;
        VlUnpacked<CData/*4:0*/, 17> __PVT__ctrl_ring__DOT__routers___05Fpos;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 17> __PVT__ctrl_ring__DOT__routers___05Frecv___05Fen;
        VlUnpacked<VlUnpacked<VlWide<8>/*228:0*/, 3>, 17> __PVT__ctrl_ring__DOT__routers___05Frecv___05Fmsg;
        VlUnpacked<VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3>, 17> __PVT__ctrl_ring__DOT__routers___05Frecv___05Fyum;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 17> __PVT__ctrl_ring__DOT__routers___05Fsend___05Fen;
        VlUnpacked<VlUnpacked<VlWide<8>/*228:0*/, 3>, 17> __PVT__ctrl_ring__DOT__routers___05Fsend___05Fmsg;
        VlUnpacked<VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3>, 17> __PVT__ctrl_ring__DOT__routers___05Fsend___05Fyum;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F0__send___05Fyum;
    };
    struct {
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F0__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F0__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F0__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F0__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F0__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F1__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F1__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F1__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F1__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F1__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F1__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F2__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F2__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F2__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F2__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F2__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F2__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F3__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F3__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F3__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F3__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F3__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F3__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F4__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F4__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F4__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F4__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F4__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F4__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F5__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F5__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F5__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F5__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F5__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F5__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F6__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F6__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F6__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F6__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F6__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F6__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F7__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F7__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F7__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F7__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F7__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F7__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F8__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F8__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F8__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F8__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F8__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F8__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F9__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F9__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F9__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F9__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F9__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F9__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F10__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F10__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F10__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F10__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F10__recv___05Fmsg;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F10__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F11__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F11__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F11__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F11__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F11__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F11__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F12__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F12__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F12__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F12__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F12__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F12__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F13__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F13__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F13__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F13__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F13__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F13__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F14__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F14__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F14__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F14__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F14__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F14__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F15__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F15__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F15__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F15__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F15__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F15__recv___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellinp__routers___05F16__send___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F16__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellout__routers___05F16__send___05Fen;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 3> ctrl_ring__DOT____Vcellout__routers___05F16__recv___05Fyum;
        VlUnpacked<VlWide<8>/*228:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F16__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> ctrl_ring__DOT____Vcellinp__routers___05F16__recv___05Fen;
        VlUnpacked<CData/*0:0*/, 17> __PVT__ctrl_ring__DOT__send_adp___05Frecv___05Fen;
        VlUnpacked<VlWide<8>/*228:0*/, 17> __PVT__ctrl_ring__DOT__send_adp___05Frecv___05Fmsg;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 17> __PVT__ctrl_ring__DOT__send_adp___05Frecv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F0__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F1__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F2__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F3__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F4__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F5__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F6__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F7__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F8__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F9__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F10__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F11__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F12__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F13__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F14__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F15__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 2> ctrl_ring__DOT____Vcellout__send_adp___05F16__recv___05Fyum;
        VlUnpacked<CData/*0:0*/, 4> __PVT__data_mem__DOT__idTo2d_x_lut;
        VlUnpacked<CData/*0:0*/, 4> __PVT__data_mem__DOT__idTo2d_y_lut;
        VlUnpacked<VlWide<3>/*88:0*/, 8> __PVT__data_mem__DOT__rd_pkt;
        VlUnpacked<VlWide<3>/*88:0*/, 8> __PVT__data_mem__DOT__wr_pkt;
        VlUnpacked<VlWide<3>/*88:0*/, 8> __PVT__data_mem__DOT__read_crossbar___05Frecv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 8> __PVT__data_mem__DOT__read_crossbar___05Frecv___05Frdy;
        VlUnpacked<CData/*0:0*/, 8> __PVT__data_mem__DOT__read_crossbar___05Frecv___05Fval;
    };
    struct {
        VlUnpacked<VlWide<3>/*88:0*/, 3> __PVT__data_mem__DOT__read_crossbar___05Fsend___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> __PVT__data_mem__DOT__read_crossbar___05Fsend___05Frdy;
        VlUnpacked<CData/*0:0*/, 3> __PVT__data_mem__DOT__read_crossbar___05Fsend___05Fval;
        VlUnpacked<VlWide<3>/*88:0*/, 3> __PVT__data_mem__DOT__response_crossbar___05Frecv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> __PVT__data_mem__DOT__response_crossbar___05Frecv___05Frdy;
        VlUnpacked<CData/*0:0*/, 3> __PVT__data_mem__DOT__response_crossbar___05Frecv___05Fval;
        VlUnpacked<VlWide<3>/*88:0*/, 8> __PVT__data_mem__DOT__response_crossbar___05Fsend___05Fmsg;
        VlUnpacked<CData/*0:0*/, 8> __PVT__data_mem__DOT__response_crossbar___05Fsend___05Frdy;
        VlUnpacked<CData/*0:0*/, 8> __PVT__data_mem__DOT__response_crossbar___05Fsend___05Fval;
        VlUnpacked<VlWide<3>/*88:0*/, 8> __PVT__data_mem__DOT__write_crossbar___05Frecv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 8> __PVT__data_mem__DOT__write_crossbar___05Frecv___05Frdy;
        VlUnpacked<CData/*0:0*/, 8> __PVT__data_mem__DOT__write_crossbar___05Frecv___05Fval;
        VlUnpacked<VlWide<3>/*88:0*/, 3> __PVT__data_mem__DOT__write_crossbar___05Fsend___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> __PVT__data_mem__DOT__write_crossbar___05Fsend___05Frdy;
        VlUnpacked<CData/*0:0*/, 3> __PVT__data_mem__DOT__write_crossbar___05Fsend___05Fval;
        VlUnpacked<CData/*3:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F0__DOT__memory___05Fraddr;
        VlUnpacked<VlWide<3>/*66:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F0__DOT__memory___05Frdata;
        VlUnpacked<CData/*3:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F0__DOT__memory___05Fwaddr;
        VlUnpacked<VlWide<3>/*66:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F0__DOT__memory___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F0__DOT__memory___05Fwen;
        VlUnpacked<VlWide<3>/*66:0*/, 16> data_mem__DOT__memory_wrapper___05F0__DOT__memory__DOT__regs;
        VlUnpacked<CData/*3:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F1__DOT__memory___05Fraddr;
        VlUnpacked<VlWide<3>/*66:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F1__DOT__memory___05Frdata;
        VlUnpacked<CData/*3:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F1__DOT__memory___05Fwaddr;
        VlUnpacked<VlWide<3>/*66:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F1__DOT__memory___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__memory_wrapper___05F1__DOT__memory___05Fwen;
        VlUnpacked<VlWide<3>/*66:0*/, 16> data_mem__DOT__memory_wrapper___05F1__DOT__memory__DOT__regs;
        VlUnpacked<VlUnpacked<VlWide<3>/*88:0*/, 8>, 3> __PVT__data_mem__DOT__response_crossbar__DOT__route_units___05Fsend___05Fmsg;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 8>, 3> __PVT__data_mem__DOT__response_crossbar__DOT__route_units___05Fsend___05Frdy;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 8>, 3> __PVT__data_mem__DOT__response_crossbar__DOT__route_units___05Fsend___05Fval;
        VlUnpacked<CData/*0:0*/, 8> data_mem__DOT__response_crossbar__DOT____Vcellout__route_units___05F0__send___05Fval;
        VlUnpacked<CData/*0:0*/, 8> data_mem__DOT__response_crossbar__DOT____Vcellinp__route_units___05F0__send___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 8> data_mem__DOT__response_crossbar__DOT____Vcellout__route_units___05F0__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 8> data_mem__DOT__response_crossbar__DOT____Vcellout__route_units___05F1__send___05Fval;
        VlUnpacked<CData/*0:0*/, 8> data_mem__DOT__response_crossbar__DOT____Vcellinp__route_units___05F1__send___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 8> data_mem__DOT__response_crossbar__DOT____Vcellout__route_units___05F1__send___05Fmsg;
        VlUnpacked<CData/*0:0*/, 8> data_mem__DOT__response_crossbar__DOT____Vcellout__route_units___05F2__send___05Fval;
        VlUnpacked<CData/*0:0*/, 8> data_mem__DOT__response_crossbar__DOT____Vcellinp__route_units___05F2__send___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 8> data_mem__DOT__response_crossbar__DOT____Vcellout__route_units___05F2__send___05Fmsg;
        VlUnpacked<VlUnpacked<VlWide<3>/*88:0*/, 3>, 8> __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05Frecv___05Fmsg;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 8> __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05Frecv___05Frdy;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 3>, 8> __PVT__data_mem__DOT__response_crossbar__DOT__switch_units___05Frecv___05Fval;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F0__recv___05Fval;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellout__switch_units___05F0__recv___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F0__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F1__recv___05Fval;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellout__switch_units___05F1__recv___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F1__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F2__recv___05Fval;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellout__switch_units___05F2__recv___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F2__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F3__recv___05Fval;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellout__switch_units___05F3__recv___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F3__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F4__recv___05Fval;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellout__switch_units___05F4__recv___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F4__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F5__recv___05Fval;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellout__switch_units___05F5__recv___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F5__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F6__recv___05Fval;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellout__switch_units___05F6__recv___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F6__recv___05Fmsg;
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F7__recv___05Fval;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellout__switch_units___05F7__recv___05Frdy;
        VlUnpacked<VlWide<3>/*88:0*/, 3> data_mem__DOT__response_crossbar__DOT____Vcellinp__switch_units___05F7__recv___05Fmsg;
        VlUnpacked<VlWide<3>/*88:0*/, 2> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__mux___05Fin_;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<3>/*88:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<3>/*88:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<3>/*88:0*/, 2> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F0__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<VlWide<3>/*88:0*/, 2> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__mux___05Fin_;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<3>/*88:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<3>/*88:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<3>/*88:0*/, 2> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F1__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
        VlUnpacked<VlWide<3>/*88:0*/, 2> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__mux___05Fin_;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Fraddr;
        VlUnpacked<VlWide<3>/*88:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Frdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Fwaddr;
        VlUnpacked<VlWide<3>/*88:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Fwdata;
        VlUnpacked<CData/*0:0*/, 1> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf___05Fwen;
        VlUnpacked<VlWide<3>/*88:0*/, 2> __PVT__data_mem__DOT__response_crossbar__DOT__input_units___05F2__DOT__queue__DOT__dpath__DOT__rf__DOT__regs;
    };

    // INTERNAL VARIABLES
    Vcgra_test__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vcgra_test_CgraRTL___05F302b5d787f9ca139(Vcgra_test__Syms* symsp, const char* v__name);
    ~Vcgra_test_CgraRTL___05F302b5d787f9ca139();
    VL_UNCOPYABLE(Vcgra_test_CgraRTL___05F302b5d787f9ca139);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
